#!/usr/bin/env python3
"""Verify the reviewed routed candidate after `forge build`; no network or signing.

The manifest is deliberately not regenerated by this command. Contract/compiler changes
require review and a new manifest. Bytecode hashes refer to compiler artifacts containing
immutable placeholders, not to a deployed address's extcodehash.
"""
import hashlib
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "releases/routed-candidate/manifest.json"


def require(condition, message):
    if not condition:
        raise ValueError(message)


def verify(root=ROOT, manifest_path=MANIFEST):
    manifest = json.loads(manifest_path.read_text())
    for path, expected in manifest["sourcesSha256"].items():
        actual = hashlib.sha256((root / path).read_bytes()).hexdigest()
        require(actual == expected, f"Reviewed source changed: {path}")
    for name, expected in manifest["contracts"].items():
        artifact = json.loads((root / f"out/{name}.sol/{name}.json").read_text())
        metadata = artifact["metadata"]
        settings = metadata["settings"]
        require(metadata["compiler"]["version"] == manifest["compiler"], f"Compiler changed: {name}")
        require(settings["optimizer"] == {"enabled": True, "runs": 1}, f"Optimizer changed: {name}")
        require(settings["evmVersion"] == "cancun", f"EVM target changed: {name}")
        require(not settings.get("viaIR", False), f"Compiler pipeline changed: {name}")
        require(settings["metadata"]["bytecodeHash"] == "none", f"Metadata settings changed: {name}")
        for field, key, limit, extra in [
            ("deployedBytecode", "runtime", 24_576, 0),
            ("bytecode", "creation", 49_152, expected["constructorArgsBytes"]),
        ]:
            code = bytes.fromhex(artifact[field]["object"].removeprefix("0x"))
            require(len(code) + extra <= limit, f"Deployment size limit exceeded: {name} {key}")
            require(len(code) == expected[f"{key}Bytes"], f"Reviewed size changed: {name} {key}")
            require(hashlib.sha256(code).hexdigest() == expected[f"{key}Sha256"],
                    f"Reviewed bytecode changed: {name} {key}")
        print(f"PASS: {name}: {expected['runtimeBytes']} runtime bytes; "
              f"{24_576 - expected['runtimeBytes']} bytes of headroom; reviewed hashes match")


if __name__ == "__main__":
    try:
        verify()
    except (ValueError, OSError, KeyError) as error:
        sys.exit(f"Release check failed: {error}")
